language: python
dist: trusty
sudo: required

python:
  - "3.6"

os:
  - linux
#  - osx
#  - windows

#matrix:
#  include:
#    - name: "Python 3.6 on Xenial Linux"
#      python: 3.6           # this works for Linux but is ignored on macOS or Windows
#
#    - name: "Python 3.6 on macOS"
#      os: osx
#      osx_image: xcode11    # Python 3.6 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
#
#    - name: "Python 3.6 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - ./scripts/cython.sh

after_success: ./scripts/clean.sh

branches:
  only:
    - master
    - develop

notifications:
  email: false
