language: python
dist: trusty
sudo: required

python:
  - "3.6"

os:
  - linux

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - ./scripts/cython.sh

after_success: ./scripts/clean.sh

branches:
  only:
    - master
    - develop

notifications:
  email: false
