language: python
dist: trusty
sudo: required

os:
  - osx
#  - linux

script:
  - ./scripts/cython.sh

after_success: ./scripts/clean.sh

branches:
  only:
    - master
    - develop

notifications:
  email: false
